/**
 * 아이콘 피커에 표시할 Lucide 아이콘 큐레이션 목록
 * (전체 번들 회피 — 자주 쓰일 것 같은 것만 명시적으로 import)
 */

import {
  File,
  FileText,
  FileCode,
  Folder,
  FolderOpen,
  Book,
  BookOpen,
  NotebookPen,
  Bookmark,
  Star,
  Heart,
  Flag,
  Pin,
  Tag,
  Home,
  Building,
  Briefcase,
  Calendar,
  Clock,
  Target,
  Lightbulb,
  Zap,
  Sparkles,
  Rocket,
  Flame,
  Sun,
  Moon,
  Cloud,
  Package,
  Box,
  Archive,
  Inbox,
  Mail,
  MessageSquare,
  Users,
  User,
  Settings,
  Search,
  Database,
  Globe,
  Layout,
  Layers,
  List,
  CheckSquare,
  Pencil,
  type LucideIcon,
} from "lucide-react";

export interface IconEntry {
  name: string;
  Icon: LucideIcon;
}

export const LUCIDE_ICONS: IconEntry[] = [
  { name: "File", Icon: File },
  { name: "FileText", Icon: FileText },
  { name: "FileCode", Icon: FileCode },
  { name: "Folder", Icon: Folder },
  { name: "FolderOpen", Icon: FolderOpen },
  { name: "Book", Icon: Book },
  { name: "BookOpen", Icon: BookOpen },
  { name: "NotebookPen", Icon: NotebookPen },
  { name: "Bookmark", Icon: Bookmark },
  { name: "Pencil", Icon: Pencil },
  { name: "CheckSquare", Icon: CheckSquare },
  { name: "List", Icon: List },
  { name: "Layout", Icon: Layout },
  { name: "Layers", Icon: Layers },
  { name: "Star", Icon: Star },
  { name: "Heart", Icon: Heart },
  { name: "Flag", Icon: Flag },
  { name: "Pin", Icon: Pin },
  { name: "Tag", Icon: Tag },
  { name: "Target", Icon: Target },
  { name: "Lightbulb", Icon: Lightbulb },
  { name: "Zap", Icon: Zap },
  { name: "Sparkles", Icon: Sparkles },
  { name: "Rocket", Icon: Rocket },
  { name: "Flame", Icon: Flame },
  { name: "Sun", Icon: Sun },
  { name: "Moon", Icon: Moon },
  { name: "Cloud", Icon: Cloud },
  { name: "Home", Icon: Home },
  { name: "Building", Icon: Building },
  { name: "Briefcase", Icon: Briefcase },
  { name: "Calendar", Icon: Calendar },
  { name: "Clock", Icon: Clock },
  { name: "Package", Icon: Package },
  { name: "Box", Icon: Box },
  { name: "Archive", Icon: Archive },
  { name: "Inbox", Icon: Inbox },
  { name: "Mail", Icon: Mail },
  { name: "MessageSquare", Icon: MessageSquare },
  { name: "Users", Icon: Users },
  { name: "User", Icon: User },
  { name: "Settings", Icon: Settings },
  { name: "Search", Icon: Search },
  { name: "Database", Icon: Database },
  { name: "Globe", Icon: Globe },
];

export const LUCIDE_ICONS_MAP = new Map(
  LUCIDE_ICONS.map((e) => [e.name, e.Icon]),
);
