"""pages 테이블에 embedding vector(1536) 컬럼 추가

Revision ID: 1f17c46be0a7
Revises: 56cf27c01e51
Create Date: 2026-04-12 20:01:50.477414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '1f17c46be0a7'
down_revision: Union[str, Sequence[str], None] = '56cf27c01e51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'embedding')
    # ### end Alembic commands ###
